### ISSUE TITLE
Không đồng bộ hiển thị giữa admin và code liquid. 

### ISSUE THREAD

**Issue by NguyenDuyPhong** [Haravan/haravan_api#2]
Hiện trạng: trên frontend, lỗi phần hình và add-to-cart 
=> Lỗi: Trong admin thì có hình, trên frontend lại không có hình.  
VD: Hiện chưa thấy lại. 
=> Lỗi: không thể dùng ajax cart/add.js để add-to-cart. 
VD: Xem sản phẩm này 
https://egany-app.myharavan.com/admin/product/#/detail/1001457531 (Tượng Ném đáo màu)

**Comment by vinh-hrv** [comment]
Đã fix

**Comment by NguyenDuyPhong** [comment]
+ Vẫn còn lỗi Add-To-Cart nè aVinh (SP này chỉ có 1 variant, là dạng KHÔNG QUẢN LÝ TỒN KHO): 
![error02-addtocart](https://cloud.githubusercontent.com/assets/5443465/12160566/d6e9d9e0-b51f-11e5-9999-2a2cd23482bd.png)

**Comment by NguyenDuyPhong** [comment]
Ngày 10/03/2016: 
- Bên QHOME báo 1 lỗi tương tự: sản phẩm có id=1001566260 (Bộ trà (13sp) Hemingway)  
https://qhome.myharavan.com/admin/product/#/detail/1001566260  
- Đ/v "tag", khi xem trong /admin và API thì ra tags giống nhau. Liquid thì thiếu tag "stock_1" (dùng code liquid product.tags)
