### ISSUE TITLE
Tại Phân Loại, trong  HRV admin khác với request API

### ISSUE THREAD

**Issue by NguyenDuyPhong** [Haravan/haravan_api#6]
hi a Vinh, kiểm tra giúp e sản phầm này nhé 

https://qhome.myharavan.com/admin/product/#/detail/1001364164   (Bộ trà 0.3L Mẫu Đơn IFP Chỉ bạch kim)    
Tại Phân Loại, Trong admin HRV thì để là "Amis", nhưng khi dùng API request thì nó là "Mẫu Đơn IFP". 
Sao HRV admin lại không hiện ra là "Mẫu Đơn IFP"  như dữ liệu từ API vậy a? 

![error43-product_type03 display wrong type at backend](https://cloud.githubusercontent.com/assets/5443465/12413303/64b4c772-bec0-11e5-8b2a-c9df4e8da515.png)
![error43-product_type mau don ifp](https://cloud.githubusercontent.com/assets/5443465/12413304/64b52c30-bec0-11e5-9e06-6bc32cff1c3a.png)

**Comment by vinh-hrv** [comment]
Fixed

**Comment by NguyenDuyPhong** [comment]
ok aVinh! :+1:
