### ISSUE TITLE
Làm sao để tạo checkout url?

### ISSUE THREAD

**Issue by lucreck** [Haravan/haravan_api#7]
Hiện tại mình cần khởi tạo checkout url cho khách hàng trên ứng dụng của công ty thông qua Haravan API, nhưng không thấy có Post Method cho Checkouts để tạo checkout url. Bạn nào biết chỉ mình cách làm sao? Cảm ơn.

**Comment by lmcuong29** [comment]
hi lucreck,

Để tạo đơn hàng thì dùng API Order nhé : https://docs.haravan.com/blogs/api-reference/1000018025-order
