### ISSUE TITLE
Lọc khách hàng theo tags?

### ISSUE THREAD

**Issue by lucreck** [Haravan/haravan_api#8]
Hiện tại em cần lọc được khách hàng theo tags. Nhưng thử 2 cách dưới đây đều không có kết quả. Không biết có cách nào không, hay khi thì có cập nhật? 
https://docs.haravan.com/blogs/api-reference/1000018017-customer
https://docs.haravan.com/blogs/api-reference/1000018006-customersavedsearch

**Comment by lmcuong25** [comment]
Hi lucreck,
Hiện tại API chưa hỗ trợ lọc khách hàng theo tags. 
anh có thể nhận webhook customer và lưu lại vào Database riêng để dùng truy vấn tự do.

**Comment by lucreck** [comment]
Ok anh Cường.
